// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniPizzaria.Infrastructure.Persistencia;

#nullable disable

namespace MiniPizzaria.Infrastructure.Migrations
{
    [DbContext(typeof(PizzariaDbContext))]
    [Migration("20261007175029_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniPizzaria.Domain.Pizza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("MiniPizzaria.Domain.Pizza", b =>
                {
                    b.OwnsMany("MiniPizzaria.Domain.Ingrediente", "Ingredientes", b1 =>
                        {
                            b1.Property<Guid>("PizzaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<bool>("Vegetariano")
                                .HasColumnType("bit");

                            b1.HasKey("PizzaId", "Id");

                            b1.ToTable("PizzaIngredientes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PizzaId");
                        });

                    b.Navigation("Ingredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
